language: java
sudo: false

matrix:
  include:
    - env: TARGETPLATFORM=mars
    - env: TARGETPLATFORM=neon
    - env: TARGETPLATFORM=oxygen
  fast_finish: true

script:
  - mvn --batch-mode -Dtarget.platform=$TARGETPLATFORM clean test

cache:
  directories:
  - $HOME/.m2
  - .mvn
